<a href="https://colab.research.google.com/github/ShubhamSShinde-U/Movies-Ticket-Price-Pridiction/blob/main/VIP_G12_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project Title: Movie Ticket Price  Pridiction 

Step No. 1 : Start

In [ ]:
#Importing All necessary Libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Now we have to import dataset 

path='/content/Movie ticket pricing (3).csv'
dataset=pd.read_csv(path)

#Printing dataset

print(dataset)        

   IMDb rating Rural Urban       Day Multiplex  Price
0           I+   yes    no    Friday        no    100
1           I-   yes    no    Sunday        no     70
2           I+   yes    no     Other        no     70
3           I-   yes    no     Other        no     50
4           I+    no   yes  Saturday       yes    300
5           I-    no   yes    Sunday       yes    250
6           I+    no   yes    Friday        no    200
7           I-    no   yes    Friday        no    150
8           I+    no   yes     Other       yes    150
9           I-    no   yes     Other        no    100
10          I-    no   yes     Other        no    100
11          I+    no   yes     Other       yes    150
12          I-    no   yes     Other        no    150
13          I+    no   yes     Other        no    200
14          I-    no   yes    Sunday       yes    250
15          I+    no   yes    Friday       yes    300
16          I+   yes    no    Friday        no    100
17          I-   yes    no  

Step No. 2 : Head and Tail function 

In [ ]:
#Using head function we are printing first 5 rows of data set

top=dataset.head()
print("The head part of dataset is ")
print(top)

#Using tail function we are printing last 5 rows of data set

bot=dataset.tail()
print("The tail part of dataset is ")
print(bot)

The head part of dataset is 
  IMDb rating Rural Urban       Day Multiplex  Price
0          I+   yes    no    Friday        no    100
1          I-   yes    no    Sunday        no     70
2          I+   yes    no     Other        no     70
3          I-   yes    no     Other        no     50
4          I+    no   yes  Saturday       yes    300
The tail part of dataset is 
   IMDb rating Rural Urban       Day Multiplex  Price
29          I-    no   yes     Other        no    100
30          I+   yes    no    Sunday        no    100
31          I-    no   yes  Saturday        no    250
32          I+    no   yes    Sunday       yes    300
33          I-   yes    no     Other        no     50


Step No . 3: Encoding 

In [ ]:
# Encoding of columns 
#Requried libraries are Imporded
#two types of encoder onehot and label encoder 
#Onehot Encoder splits the column into multiple columns which is difficult to handle


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
dataset['Rural']=le.fit_transform(dataset['Rural'])
dataset['Urban']=le.fit_transform(dataset['Urban'])
dataset['Day']=le.fit_transform(dataset['Day'])
dataset['Multiplex']=le.fit_transform(dataset['Multiplex'])
dataset['IMDb rating']=le.fit_transform(dataset['IMDb rating'])
dataset

IMDb rating  Rural  Urban  Day  Multiplex  Price
0             0      1      0    0          0    100
1             1      1      0    3          0     70
2             0      1      0    1          0     70
3             1      1      0    1          0     50
4             0      0      1    2          1    300
5             1      0      1    3          1    250
6             0      0      1    0          0    200
7             1      0      1    0          0    150
8             0      0      1    1          1    150
9             1      0      1    1          0    100
10            1      0      1    1          0    100
11            0      0      1    1          1    150
12            1      0      1    1          0    150
13            0      0      1    1          0    200
14            1      0      1    3          1    250
15            0      0      1    0          1    300
16            0      1      0    0          0    100
17            1      1      0    3          0     70
18            0      1      0    1          0     70
19            1      1      0    1          0     50
20            0      0      1    3          1    300
21            0      1      0    0          0    100
22            1      0      1    3          1    250
23            1      1      0    2          0     70
24            0      0      1    3          0    200
25            0      1      0    1          0     70
26            1      0      1    0          0    150
27            1      1      0    1          0     50
28            0      0      1    1          1    150
29            1      0      1    1          0    100
30            0      1      0    3          0    100
31            1      0      1    2          0    250
32            0      0      1    3          1    300
33            1      1      0    1          0     50

Step No. 4 : Dependent and Non-dependent

In [ ]:
#Differentiating Dependent and non-dependent attributes in x and y

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
x

array([[0, 1, 0, 0, 0],
       [1, 1, 0, 3, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 2, 1],
       [1, 0, 1, 3, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 3, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 1, 0, 3, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 3, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 1, 3, 1],
       [1, 1, 0, 2, 0],
       [0, 0, 1, 3, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 3, 0],
       [1, 0, 1, 2, 0],
       [0, 0, 1, 3, 1],
       [1, 1, 0, 1, 0]])

In [ ]:
y

array([100,  70,  70,  50, 300, 250, 200, 150, 150, 100, 100, 150, 150,
       200, 250, 300, 100,  70,  70,  50, 300, 100, 250,  70, 200,  70,
       150,  50, 150, 100, 100, 250, 300,  50])

Step No.5 : Sliting

In [ ]:
#Spliting of data
#Now we are giving data to train the model and to test

from pandas.core.common import random_state
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=1)

In [ ]:
xtrain

array([[0, 1, 0, 3, 0],
       [1, 1, 0, 3, 0],
       [1, 0, 1, 3, 1],
       [0, 0, 1, 2, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 1, 0, 2, 0],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 3, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 3, 1],
       [0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 2, 0],
       [0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0]])

In [ ]:
xtest

array([[1, 0, 1, 3, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 3, 1],
       [1, 0, 1, 0, 0],
       [0, 0, 1, 3, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 3, 0]])

In [ ]:
ytrain

array([100,  70, 250, 300,  70, 100,  70, 100, 100, 150,  70, 200, 200,
       150,  50,  70, 100, 100, 300, 250, 150, 100, 250, 150, 150])

In [ ]:
ytest

array([250,  50,  50,  50, 300, 150, 300,  70, 200])

Step No. 6 : Fiting Model and Accuracy Measurement

In [ ]:
# Fitting multiple linear Regression to the dataset

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures


model = LinearRegression()
model.fit(xtrain, ytrain)
y_pred = model.predict(xtest)

rmse = np.sqrt(mean_squared_error(ytest,y_pred))

#Checking accuracy of model

r2 = r2_score(ytest,y_pred)
print(rmse)
print("Model Accuracy:",r2*100,'%')


27.124303300217335
Model Accuracy: 92.90717041284258 %


Step No.7 : Manual Prediction

In [ ]:
# Manually prediction of price  with sklearn library

import numpy as np
A=np.array([[0, 0, 0, 0, 0]])
print ("Ticket price is approximately:",model.predict(A),'Rs')

Ticket price is approximately: [122.57222978] Rs
